/**:
  ros__parameters:
    car_tracker: "linear_motion_tracker"
    truck_tracker: "linear_motion_tracker"
    bus_tracker: "linear_motion_tracker"
    trailer_tracker: "linear_motion_tracker"
    pedestrian_tracker: "linear_motion_tracker"
    bicycle_tracker: "linear_motion_tracker"
    motorcycle_tracker: "linear_motion_tracker"
